unit ConstVar;

interface

    //µ˜ ‘√¸¡Ó
const
  LINEBPTEXT = 'Line Breakpoint';
  FUNCTIONBPTEXT= 'Method Breakpoint';
  EXCEPTIONBPTEXT = 'Exception Breakpoint';

  VARNOTACCESS = 'inaccessible';
  DEBUGSERVERCENTERCLASS = 'com.jdev.common.debug.server.DebugServerCenter';
  REQUEST_CREATE = 1;
  REQUEST_RUN = 2 ;
  REQUEST_DEBUG = 3;
  REQUEST_EXIT = 4;

  //œÏ”¶√¸¡Ó
  REPLY_VM_LISTEN = 10;
  REPLY_VM_CONNECT = 11;
  REPLY_VM_START = 12;
  REPLY_VM_INTERRUPT = 13;
  REPLY_VM_DISCONNECT = 14;
  REPLY_VM_DEATH = 15;


  REPLY_EXIT = 21;
  REPLY_DEBUG = 22;

  REPLY_THREAD_ADD = 23;
  REPLY_THREAD_DELETE = 24;
  REPLY_THREAD_FRAMES = 25;
  REPLY_THREAD_LIST = 26;
  REPLY_THREAD_RESUME = 27;
  REPLY_THREAD_SUSPEND = 28;

  REPLY_CLASS_LOAD = 31;
  REPLY_CLASS_UNLOAD = 32;
  REPLY_CLASS_LIST  = 33;

  REPLY_FRAME_LOCALS = 40;
  REPLY_SETBREAKPOINT = 41;
  REPLY_CLEARBREAKPOINT = 42;

  REPLY_LOCAL_DUMP = 43;
  REPLY_LOCAL_DUMPBATCH = 44;
  REPLY_LOCAL_PRINT = 45;
  REPLY_LOCAL_GETVALUE = 46;

  THREAD_STATUS_UNKNOWN  = -1;
  THREAD_STATUS_ZOMBIE   = 0;
  THREAD_STATUS_RUNNING  = 1;
  THREAD_STATUS_SLEEPING = 2;
  THREAD_STATUS_MONITOR  = 3;
  THREAD_STATUS_WAIT     = 4;
  THREAD_STATUS_NOT_STARTED = 5;

  THREAD_ICON_UNKNOWN  = 3;
  THREAD_ICON_ZOMBIE   = 3;
  THREAD_ICON_RUNNING  = 4;
  THREAD_ICON_SLEEPING = 5;
  THREAD_ICON_MONITOR  = 6;
  THREAD_ICON_WAIT     = 7;
  THREAD_ICON_NOT_STARTED = 3;
  THREAD_ICON_SUSPEND = 8;


  LINEBREAKPOINT = '0';
  METHODBREAKPOINT = '1';
  EXCEPTIONBREAKPOINT = '2';

  SHOW_MAX_CHILDNODE = 500;
implementation

end.
